# Copyright (c) 2026 Iyad Engle. All rights reserved.
# Licensed under the MIT License. See LICENSE file for details.

"""HTML report exporter."""

from __future__ import annotations

import html as html_module
from pathlib import Path

from netdiag.utils.models import ScanReport, SecurityStatus, Status


def export_html(report: ScanReport, filepath: str | None = None) -> str:
    e = html_module.escape

    status_colors = {s.value: c for s, c in [
        (Status.PASS, "#3fb950"), (Status.FAIL, "#f85149"), (Status.WARN, "#d29922"),
        (Status.SKIP, "#8b949e"), (Status.ERROR, "#f85149"),
    ]}
    security_status_colors = {s.value: c for s, c in [
        (SecurityStatus.FAIL, "#f85149"), (SecurityStatus.OBSERVATION, "#58a6ff"),
        (SecurityStatus.PASS, "#3fb950"), (SecurityStatus.SKIP, "#8b949e"),
        (SecurityStatus.ERROR, "#d29922"), (SecurityStatus.INCONCLUSIVE, "#d29922"),
    ]}

    diag_rows = ""
    for r in report.results:
        color = status_colors.get(r.status.value, "#8b949e")
        diag_rows += f'<tr><td><span class="badge" style="background:{color}22;color:{color}">{e(r.status.value)}</span></td><td>{e(r.test_name)}</td><td>{e(r.evidence)}</td><td>{r.duration_ms:.0f}ms</td></tr>'

    finding_rows = ""
    for f in report.findings:
        color = security_status_colors.get(f.status.value, "#8b949e")
        finding_rows += f'''<div class="finding" style="border-left:4px solid {color}">
<div class="finding-header"><span class="badge" style="background:{color}22;color:{color}">{e(f.status.value)}</span><strong>{e(f.title)}</strong></div>
<p><strong>Evidence:</strong> {e(f.evidence)}</p><p><strong>Recommendation:</strong> {e(f.recommendation)}</p>
<p class="meta">Test: {e(f.test_name)} | Confidence: {e(f.confidence.value)}</p></div>'''

    findings_section = f'<h2>Security Findings ({len(report.findings)})</h2>{finding_rows or "<p class=muted>No security findings.</p>"}'

    html_content = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>NetDiag Report - {e(report.target)}</title>
<style>*{{margin:0;padding:0;box-sizing:border-box}}body{{font-family:-apple-system,'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:20px}}.container{{max-width:1000px;margin:0 auto}}h1{{color:#58a6ff;margin-bottom:8px}}h2{{color:#58a6ff;margin:24px 0 12px;padding-bottom:8px;border-bottom:1px solid #30363d}}.meta{{color:#8b949e;font-size:13px}}.badge{{padding:2px 8px;border-radius:12px;font-size:11px;font-weight:700}}table{{width:100%;border-collapse:collapse;margin:12px 0}}th,td{{padding:10px 12px;text-align:left;border-bottom:1px solid #30363d}}th{{background:#161b22;color:#58a6ff}}.finding{{background:#161b22;border-radius:8px;padding:16px;margin:12px 0}}.finding-header{{display:flex;align-items:center;gap:8px;margin-bottom:8px}}.finding p{{margin:4px 0;font-size:14px}}.muted{{color:#8b949e}}.summary{{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}}.summary-card{{background:#161b22;border-radius:8px;padding:16px;text-align:center}}.summary-card .num{{font-size:28px;font-weight:700}}.footer{{margin-top:32px;padding-top:16px;border-top:1px solid #30363d;color:#8b949e;font-size:13px}}</style>
</head><body><div class="container">
<h1>🛡️ NetDiag-Toolkit Report</h1>
<p class="meta">Target: <strong>{e(report.target)}</strong> | Version: {report.tool_version} | {e(report.started_at)}</p>
<div class="summary">
<div class="summary-card"><div class="num" style="color:#3fb950">{report.passed}</div>Passed</div>
<div class="summary-card"><div class="num" style="color:#f85149">{report.failed}</div>Failed</div>
<div class="summary-card"><div class="num" style="color:#d29922">{report.warned}</div>Warned</div>
<div class="summary-card"><div class="num" style="color:#f85149">{report.errors}</div>Errors</div>
<div class="summary-card"><div class="num" style="color:#58a6ff">{len(report.findings)}</div>Findings</div>
</div>
<h2>Diagnostics ({len(report.results)})</h2>
<table><tr><th>Status</th><th>Test</th><th>Evidence</th><th>Duration</th></tr>{diag_rows}</table>
{findings_section}
<div class="footer"><p>Generated by NetDiag-Toolkit v{report.tool_version} | Copyright (c) 2026 Iyad Engle | For authorized use only</p></div>
</div></body></html>'''

    if filepath:
        Path(filepath).write_text(html_content, encoding="utf-8")
    return html_content
